### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by Lewiscowles1986** [dimadin/disable-google-fonts#8]
Which PHP version(s) does this plugin target. I've not encountered a compatibility problem, but it is something you can require in composer.json so it's explicitly out-there for people

**Comment by dimadin** [comment]
What compatibility problem? It should be PHP 5.2+ because I don't use anything from newer PHP versions, though I can't confirm again right now until I find that old installation.

**Comment by Lewiscowles1986** [comment]
> I've ***not*** encountered a compatibility problem

The reason I'm asking which PHP versions this targets is so that you can specify a minimum PHP version in `composer.json`, or I can PR one.

**Comment by dimadin** [comment]
Sorry, I didn’t read it thoroughly.
